# -*- coding: utf-8 -*-
"""Homework1-RTML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vS1oro5ssu-pkRl88U0mh_OqGNeimvFS
"""

# ============================================================
# Homework 1 - RTML (ECGR-4106/5106)
# Modified AlexNet, VGGNet, and ResNet on CIFAR-10
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from sklearn.metrics import confusion_matrix
import seaborn as sns
import time
import random
from torchsummary import summary

# Set random seed for reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.backends.cudnn.deterministic = True

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')
print(f'Random seed: {SEED}')

# ============================================================
# Data Loading & Augmentation (shared across all problems)
# ============================================================

# CIFAR-10 normalization constants (mean and std for R,G,B)
CIFAR_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR_STD  = (0.2023, 0.1994, 0.2010)

train_transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
])

test_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
])

# Download CIFAR-10
full_train = torchvision.datasets.CIFAR10(root='./data', train=True,
                                          download=True, transform=train_transform)
test_set   = torchvision.datasets.CIFAR10(root='./data', train=False,
                                          download=True, transform=test_transform)

# Split train into 45k train / 5k validation
train_size = 45000
val_size   = 5000
train_set, val_set = torch.utils.data.random_split(
    full_train, [train_size, val_size],
    generator=torch.Generator().manual_seed(SEED)
)

# Override val set transform to test_transform (no augmentation)
val_set.dataset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                                download=False, transform=test_transform)

BATCH_SIZE = 128
train_loader = torch.utils.data.DataLoader(train_set, batch_size=BATCH_SIZE,
                                            shuffle=True, num_workers=2, pin_memory=True)
val_loader   = torch.utils.data.DataLoader(val_set, batch_size=BATCH_SIZE,
                                            shuffle=False, num_workers=2, pin_memory=True)
test_loader  = torch.utils.data.DataLoader(test_set, batch_size=BATCH_SIZE,
                                            shuffle=False, num_workers=2, pin_memory=True)

CLASSES = ('plane','car','bird','cat','deer','dog','frog','horse','ship','truck')
print(f'Train: {len(train_set)}, Val: {len(val_set)}, Test: {len(test_set)}')
print(f'Batch size: {BATCH_SIZE}')

# ============================================================
# Utility Functions: training loop, eval, plotting
# ============================================================

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss, correct, total = 0.0, 0, 0
    for inputs, targets in loader:
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * inputs.size(0)
        _, predicted = outputs.max(1)
        correct += predicted.eq(targets).sum().item()
        total += inputs.size(0)
    return total_loss / total, 100.0 * correct / total

def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, targets in loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            total_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            correct += predicted.eq(targets).sum().item()
            total += inputs.size(0)
    return total_loss / total, 100.0 * correct / total

def get_all_preds(model, loader, device):
    all_preds, all_labels = [], []
    model.eval()
    with torch.no_grad():
        for inputs, targets in loader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            _, preds = outputs.max(1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(targets.numpy())
    return np.array(all_preds), np.array(all_labels)

def plot_curves(train_losses, val_losses, val_accs, title, labels=None):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(title, fontsize=14)
    if labels is None:
        labels = [f'run {i}' for i in range(len(train_losses))]
    for i, (tl, vl, va) in enumerate(zip(train_losses, val_losses, val_accs)):
        epochs = range(1, len(tl)+1)
        ax1.plot(epochs, tl, linestyle='--', label=f'{labels[i]} train')
        ax1.plot(epochs, vl, label=f'{labels[i]} val')
        ax2.plot(epochs, va, label=labels[i])
    ax1.set_xlabel('Epoch'); ax1.set_ylabel('Loss')
    ax1.set_title('Loss Curves'); ax1.legend()
    ax2.set_xlabel('Epoch'); ax2.set_ylabel('Accuracy (%)')
    ax2.set_title('Val Accuracy'); ax2.legend()
    plt.tight_layout(); plt.show()

def plot_confusion_matrix(preds, labels, classes, title):
    cm = confusion_matrix(labels, preds)
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=classes, yticklabels=classes, ax=ax)
    ax.set_xlabel('Predicted'); ax.set_ylabel('True')
    ax.set_title(title); plt.tight_layout(); plt.show()

def visualize_first_layer_filters(model, first_conv_attr, title):
    conv = first_conv_attr
    filters = conv.weight.data.cpu().clone()
    # Normalize per filter
    n_filters = min(filters.shape[0], 32)
    fig, axes = plt.subplots(4, 8, figsize=(12, 6))
    fig.suptitle(title)
    for idx, ax in enumerate(axes.flat):
        if idx < n_filters:
            f = filters[idx]
            f = f - f.min(); f = f / (f.max() + 1e-8)
            if f.shape[0] == 3:
                ax.imshow(f.permute(1,2,0).numpy())
            else:
                ax.imshow(f[0].numpy(), cmap='gray')
        ax.axis('off')
    plt.tight_layout(); plt.show()

def train_model(model, train_loader, val_loader, n_epochs, lr=0.01,
                weight_decay=5e-4, scheduler_type='cosine', device=device):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9,
                          weight_decay=weight_decay)
    if scheduler_type == 'cosine':
        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs)
    else:
        scheduler = optim.lr_scheduler.MultiStepLR(optimizer,
                                                    milestones=[int(n_epochs*0.5), int(n_epochs*0.75)],
                                                    gamma=0.1)
    train_losses, val_losses, val_accs = [], [], []
    best_val_acc = 0.0
    start = time.time()
    for epoch in range(1, n_epochs+1):
        t_loss, t_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        v_loss, v_acc = evaluate(model, val_loader, criterion, device)
        scheduler.step()
        train_losses.append(t_loss); val_losses.append(v_loss); val_accs.append(v_acc)
        if v_acc > best_val_acc:
            best_val_acc = v_acc
        if epoch % 5 == 0 or epoch == 1:
            print(f'Epoch {epoch:3d}/{n_epochs} | '
                  f'T-Loss: {t_loss:.4f} T-Acc: {t_acc:.2f}% | '
                  f'V-Loss: {v_loss:.4f} V-Acc: {v_acc:.2f}%')
    elapsed = time.time() - start
    print(f'\nTraining complete in {elapsed/60:.1f} min | Best Val Acc: {best_val_acc:.2f}%')
    print(f'Time per epoch: {elapsed/n_epochs:.1f}s')
    return train_losses, val_losses, val_accs, elapsed

print('Utility functions defined.')

# ============================================================
# PROBLEM 1A: Modified AlexNet for CIFAR-10 (32x32)
# ============================================================
# Modifications vs. original AlexNet (227x227, 61M params):
# 1. First conv: 11x11 stride 4 -> 3x3 stride 1 (32x32 spatial dims preserved)
# 2. Removed first MaxPool (would collapse 32x32 too early)
# 3. Conv2: 5x5 -> 3x3
# 4. Only 1 MaxPool after Conv2 (stride 2), plus 1 after Conv5
# 5. FC layers: 4096->4096->1000 -> 1024->512->10 (drastically fewer params)
# 6. Filter counts halved throughout

class ModifiedAlexNet(nn.Module):
    def __init__(self, dropout_p=0.0):
        super(ModifiedAlexNet, self).__init__()
        self.features = nn.Sequential(
            # Block 1: 32->32
            nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1),  # 32x32
            nn.ReLU(inplace=True),
            # Block 2: 32->16
            nn.Conv2d(32, 64, kernel_size=3, padding=1),            # 32x32
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),                  # 16x16
            # Block 3: 16->16
            nn.Conv2d(64, 128, kernel_size=3, padding=1),           # 16x16
            nn.ReLU(inplace=True),
            # Block 4: 16->16
            nn.Conv2d(128, 128, kernel_size=3, padding=1),          # 16x16
            nn.ReLU(inplace=True),
            # Block 5: 16->8
            nn.Conv2d(128, 64, kernel_size=3, padding=1),           # 16x16
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),                  # 8x8
        )
        self.classifier = nn.Sequential(
            nn.Dropout(p=dropout_p),
            nn.Linear(64 * 8 * 8, 1024),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout_p),
            nn.Linear(1024, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

# Instantiate baseline (no dropout)
alexnet_base = ModifiedAlexNet(dropout_p=0.0).to(device)
print('=== Modified AlexNet (Baseline, no dropout) ===')
summary(alexnet_base, (3, 32, 32))
print(f'\nOriginal AlexNet params: ~61,100,840')

# ============================================================
# PROBLEM 1A: Train baseline AlexNet (30 epochs)
# ============================================================
print('Training P1A: Modified AlexNet - Baseline (no dropout), 30 epochs')
print('Hyperparams: SGD lr=0.1, momentum=0.9, wd=5e-4, CosineAnnealingLR, batch=128')

alexnet_base = ModifiedAlexNet(dropout_p=0.0).to(device)
p1a_tl, p1a_vl, p1a_va, p1a_time = train_model(
    alexnet_base, train_loader, val_loader,
    n_epochs=30, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)

# Test accuracy
crit = nn.CrossEntropyLoss()
_, p1a_test_acc = evaluate(alexnet_base, test_loader, crit, device)
print(f'\nP1A Test Accuracy: {p1a_test_acc:.2f}%')

# Plot curves
plot_curves([p1a_tl], [p1a_vl], [p1a_va],
            'P1A: Modified AlexNet - Baseline', labels=['Baseline (p=0.0)'])

# Confusion matrix
p1a_preds, p1a_labels = get_all_preds(alexnet_base, test_loader, device)
plot_confusion_matrix(p1a_preds, p1a_labels, CLASSES, 'P1A Confusion Matrix - Modified AlexNet Baseline')

# Visualize first-layer filters
visualize_first_layer_filters(alexnet_base, alexnet_base.features[0],
                               'P1A: First Conv Layer Filters (32 filters, 3x3x3)')

# ============================================================
# PROBLEM 1B: AlexNet with Dropout (p=0.3 and p=0.5)
# ============================================================
print('Training P1B: Modified AlexNet with Dropout p=0.3')
alexnet_d03 = ModifiedAlexNet(dropout_p=0.3).to(device)
p1b03_tl, p1b03_vl, p1b03_va, _ = train_model(
    alexnet_d03, train_loader, val_loader,
    n_epochs=30, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p1b03_test = evaluate(alexnet_d03, test_loader, nn.CrossEntropyLoss(), device)
print(f'P1B (p=0.3) Test Acc: {p1b03_test:.2f}%')

print('\nTraining P1B: Modified AlexNet with Dropout p=0.5')
alexnet_d05 = ModifiedAlexNet(dropout_p=0.5).to(device)
p1b05_tl, p1b05_vl, p1b05_va, _ = train_model(
    alexnet_d05, train_loader, val_loader,
    n_epochs=30, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p1b05_test = evaluate(alexnet_d05, test_loader, nn.CrossEntropyLoss(), device)
print(f'P1B (p=0.5) Test Acc: {p1b05_test:.2f}%')

# Compare all three AlexNet variants
plot_curves(
    [p1a_tl, p1b03_tl, p1b05_tl],
    [p1a_vl, p1b03_vl, p1b05_vl],
    [p1a_va, p1b03_va, p1b05_va],
    'P1B: AlexNet - Baseline vs Dropout Comparison',
    labels=['Baseline (p=0)', 'Dropout p=0.3', 'Dropout p=0.5']
)

p1b03_preds, _ = get_all_preds(alexnet_d03, test_loader, device)
plot_confusion_matrix(p1b03_preds, p1a_labels, CLASSES, 'P1B Confusion Matrix - AlexNet Dropout p=0.3')

p1b05_preds, _ = get_all_preds(alexnet_d05, test_loader, device)
plot_confusion_matrix(p1b05_preds, p1a_labels, CLASSES, 'P1B Confusion Matrix - AlexNet Dropout p=0.5')

print('\n=== P1 Summary ===')
print(f'  Baseline (p=0):  {p1a_test_acc:.2f}%')
print(f'  Dropout p=0.3:   {p1b03_test:.2f}%')
print(f'  Dropout p=0.5:   {p1b05_test:.2f}%')

# ============================================================
# PROBLEM 2A: Modified VGGNet for CIFAR-10
# ============================================================
# VGG configurations: A=VGG-11, B=VGG-13, D=VGG-16, E=VGG-19
# We choose VGG-11 adapted to match our AlexNet param count (~5.5M)
# Modifications for 32x32 CIFAR-10:
# 1. Reduce MaxPool from 5 to 3 (keeping 3 pool layers: 32->16->8->4)
# 2. FC layers: 4096->4096->1000 -> 512->256->10
# 3. All 3x3 conv kernels kept (VGG's core design)

VGG_CFGS = {
    'VGG11': [64, 'M', 128, 'M', 256, 256, 'M', 512, 512],  # 3 pool layers for 32x32
}

class AdaptedVGG(nn.Module):
    def __init__(self, cfg_name='VGG11', dropout_p=0.0):
        super(AdaptedVGG, self).__init__()
        cfg = VGG_CFGS[cfg_name]
        layers = []
        in_ch = 3
        for v in cfg:
            if v == 'M':
                layers.append(nn.MaxPool2d(kernel_size=2, stride=2))
            else:
                layers += [nn.Conv2d(in_ch, v, kernel_size=3, padding=1),
                           nn.ReLU(inplace=True)]
                in_ch = v
        self.features = nn.Sequential(*layers)
        # After 3 MaxPools: 32->16->8->4, 512 channels -> 512*4*4=8192
        self.classifier = nn.Sequential(
            nn.Dropout(p=dropout_p),
            nn.Linear(512 * 4 * 4, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout_p),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Linear(256, 10),
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

vgg_base = AdaptedVGG('VGG11', dropout_p=0.0).to(device)
print('=== Adapted VGG-11 for CIFAR-10 ===')
summary(vgg_base, (3, 32, 32))

# ============================================================
# PROBLEM 2A: Train VGG-11 baseline
# ============================================================
print('Training P2A: Adapted VGG-11 - Baseline (no dropout), 30 epochs')
vgg_base = AdaptedVGG('VGG11', dropout_p=0.0).to(device)
p2a_tl, p2a_vl, p2a_va, p2a_time = train_model(
    vgg_base, train_loader, val_loader,
    n_epochs=30, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)

crit = nn.CrossEntropyLoss()
_, p2a_test_acc = evaluate(vgg_base, test_loader, crit, device)
print(f'\nP2A Test Accuracy: {p2a_test_acc:.2f}%')

plot_curves([p2a_tl], [p2a_vl], [p2a_va],
            'P2A: Adapted VGG-11 Baseline', labels=['VGG-11 Baseline'])

p2a_preds, p2a_labels = get_all_preds(vgg_base, test_loader, device)
plot_confusion_matrix(p2a_preds, p2a_labels, CLASSES, 'P2A Confusion Matrix - Adapted VGG-11 Baseline')

visualize_first_layer_filters(vgg_base, vgg_base.features[0],
                               'P2A: VGG-11 First Conv Layer Filters')

# AlexNet vs VGGNet comparison
print('\n=== AlexNet vs VGGNet Architecture Comparison ===')
print(f'  Modified AlexNet - Test Acc: {p1a_test_acc:.2f}% | Time/epoch: {p1a_time/30:.1f}s')
print(f'  Adapted VGG-11   - Test Acc: {p2a_test_acc:.2f}% | Time/epoch: {p2a_time/30:.1f}s')

# ============================================================
# PROBLEM 2B: VGG-11 with Dropout
# ============================================================
print('Training P2B: VGG-11 Dropout p=0.3')
vgg_d03 = AdaptedVGG('VGG11', dropout_p=0.3).to(device)
p2b03_tl, p2b03_vl, p2b03_va, _ = train_model(
    vgg_d03, train_loader, val_loader,
    n_epochs=30, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p2b03_test = evaluate(vgg_d03, test_loader, nn.CrossEntropyLoss(), device)
print(f'P2B VGG p=0.3 Test Acc: {p2b03_test:.2f}%')

print('\nTraining P2B: VGG-11 Dropout p=0.5')
vgg_d05 = AdaptedVGG('VGG11', dropout_p=0.5).to(device)
p2b05_tl, p2b05_vl, p2b05_va, _ = train_model(
    vgg_d05, train_loader, val_loader,
    n_epochs=30, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p2b05_test = evaluate(vgg_d05, test_loader, nn.CrossEntropyLoss(), device)
print(f'P2B VGG p=0.5 Test Acc: {p2b05_test:.2f}%')

plot_curves(
    [p2a_tl, p2b03_tl, p2b05_tl],
    [p2a_vl, p2b03_vl, p2b05_vl],
    [p2a_va, p2b03_va, p2b05_va],
    'P2B: VGG-11 - Baseline vs Dropout',
    labels=['VGG-11 Baseline', 'Dropout p=0.3', 'Dropout p=0.5']
)

print('\n=== P2 Summary ===')
print(f'  VGG Baseline:    {p2a_test_acc:.2f}%')
print(f'  VGG p=0.3:       {p2b03_test:.2f}%')
print(f'  VGG p=0.5:       {p2b05_test:.2f}%')
# ============================================================
# PROBLEM 3: ResNet-11 and ResNet-18 for CIFAR-10
# ============================================================

class BasicBlock(nn.Module):
    """Standard BasicBlock with BN: conv->BN->ReLU->conv->BN + skip"""
    def __init__(self, in_planes, planes, stride=1):
        super(BasicBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, 3, stride=stride, padding=1, bias=False)
        self.bn1   = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, 3, stride=1, padding=1, bias=False)
        self.bn2   = nn.BatchNorm2d(planes)
        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, planes, 1, stride=stride, bias=False),
                nn.BatchNorm2d(planes)
            )

    def forward(self, x):
        out = torch.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        return torch.relu(out)


class ResNetCIFAR(nn.Module):
    """Flexible ResNet for CIFAR-10 (32x32 input, single 3x3 stem, no initial pool)"""
    def __init__(self, block, stage_layers, dropout_p=0.0):
        """
        stage_layers: list of (planes, n_blocks, stride) per stage
        """
        super(ResNetCIFAR, self).__init__()
        self.stem = nn.Sequential(
            nn.Conv2d(3, 64, 3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True)
        )
        layers = []
        in_planes = 64
        for planes, n_blocks, stride in stage_layers:
            layers.append(block(in_planes, planes, stride=stride))
            in_planes = planes
            for _ in range(1, n_blocks):
                layers.append(block(in_planes, planes, stride=1))
        self.layers = nn.Sequential(*layers)
        self.gap = nn.AdaptiveAvgPool2d(1)
        self.dropout = nn.Dropout(p=dropout_p)
        self.fc = nn.Linear(in_planes, 10)

    def forward(self, x):
        x = self.stem(x)
        x = self.layers(x)
        x = self.gap(x)
        x = x.view(x.size(0), -1)
        x = self.dropout(x)
        x = self.fc(x)
        return x


def resnet11_cifar(dropout_p=0.0):
    """ResNet-11: 4 stages with 1 BasicBlock each (1+2+2+2+2+2 = ~11 weight layers)"""
    return ResNetCIFAR(BasicBlock, [
        (64,  1, 1),
        (128, 1, 2),
        (256, 1, 2),
        (512, 1, 2),
    ], dropout_p=dropout_p)


def resnet18_cifar(dropout_p=0.0):
    """ResNet-18: 4 stages with 2 BasicBlocks each"""
    return ResNetCIFAR(BasicBlock, [
        (64,  2, 1),
        (128, 2, 2),
        (256, 2, 2),
        (512, 2, 2),
    ], dropout_p=dropout_p)


print('=== ResNet-11 for CIFAR-10 ===')
resnet11 = resnet11_cifar().to(device)
summary(resnet11, (3, 32, 32))

print('\n=== ResNet-18 for CIFAR-10 ===')
resnet18 = resnet18_cifar().to(device)
summary(resnet18, (3, 32, 32))

# ============================================================
# PROBLEM 3A: Train ResNet-11 and ResNet-18 (50 epochs)
# ============================================================
print('Training P3A: ResNet-11 Baseline, 50 epochs')
resnet11 = resnet11_cifar(dropout_p=0.0).to(device)
p3a11_tl, p3a11_vl, p3a11_va, p3a11_time = train_model(
    resnet11, train_loader, val_loader,
    n_epochs=50, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p3a11_test = evaluate(resnet11, test_loader, nn.CrossEntropyLoss(), device)
print(f'\nP3A ResNet-11 Test Acc: {p3a11_test:.2f}%')

print('\nTraining P3A: ResNet-18 Baseline, 50 epochs')
resnet18 = resnet18_cifar(dropout_p=0.0).to(device)
p3a18_tl, p3a18_vl, p3a18_va, p3a18_time = train_model(
    resnet18, train_loader, val_loader,
    n_epochs=50, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p3a18_test = evaluate(resnet18, test_loader, nn.CrossEntropyLoss(), device)
print(f'\nP3A ResNet-18 Test Acc: {p3a18_test:.2f}%')

# Plot
plot_curves(
    [p3a11_tl, p3a18_tl],
    [p3a11_vl, p3a18_vl],
    [p3a11_va, p3a18_va],
    'P3A: ResNet-11 vs ResNet-18 Baseline',
    labels=['ResNet-11', 'ResNet-18']
)

p3a11_preds, p3a_labels = get_all_preds(resnet11, test_loader, device)
plot_confusion_matrix(p3a11_preds, p3a_labels, CLASSES, 'P3A Confusion Matrix - ResNet-11')

p3a18_preds, _ = get_all_preds(resnet18, test_loader, device)
plot_confusion_matrix(p3a18_preds, p3a_labels, CLASSES, 'P3A Confusion Matrix - ResNet-18')

print(f'\nResNet-11: {p3a11_test:.2f}% | {p3a11_time/50:.1f}s/epoch')
print(f'ResNet-18: {p3a18_test:.2f}% | {p3a18_time/50:.1f}s/epoch')

# ============================================================
# PROBLEM 3B: ResNet Dropout + Final Grand Comparison
# ============================================================
print('Training P3B: ResNet-11 + Dropout p=0.3')
rn11_d03 = resnet11_cifar(dropout_p=0.3).to(device)
p3b11d03_tl, p3b11d03_vl, p3b11d03_va, _ = train_model(
    rn11_d03, train_loader, val_loader,
    n_epochs=50, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p3b11d03_test = evaluate(rn11_d03, test_loader, nn.CrossEntropyLoss(), device)
print(f'RN11 p=0.3 Test: {p3b11d03_test:.2f}%')

print('\nTraining P3B: ResNet-11 + Dropout p=0.5')
rn11_d05 = resnet11_cifar(dropout_p=0.5).to(device)
p3b11d05_tl, p3b11d05_vl, p3b11d05_va, _ = train_model(
    rn11_d05, train_loader, val_loader,
    n_epochs=50, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p3b11d05_test = evaluate(rn11_d05, test_loader, nn.CrossEntropyLoss(), device)
print(f'RN11 p=0.5 Test: {p3b11d05_test:.2f}%')

print('\nTraining P3B: ResNet-18 + Dropout p=0.3')
rn18_d03 = resnet18_cifar(dropout_p=0.3).to(device)
p3b18d03_tl, p3b18d03_vl, p3b18d03_va, _ = train_model(
    rn18_d03, train_loader, val_loader,
    n_epochs=50, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p3b18d03_test = evaluate(rn18_d03, test_loader, nn.CrossEntropyLoss(), device)
print(f'RN18 p=0.3 Test: {p3b18d03_test:.2f}%')

print('\nTraining P3B: ResNet-18 + Dropout p=0.5')
rn18_d05 = resnet18_cifar(dropout_p=0.5).to(device)
p3b18d05_tl, p3b18d05_vl, p3b18d05_va, _ = train_model(
    rn18_d05, train_loader, val_loader,
    n_epochs=50, lr=0.1, weight_decay=5e-4, scheduler_type='cosine', device=device
)
_, p3b18d05_test = evaluate(rn18_d05, test_loader, nn.CrossEntropyLoss(), device)
print(f'RN18 p=0.5 Test: {p3b18d05_test:.2f}%')

plot_curves(
    [p3a11_tl, p3b11d03_tl, p3b11d05_tl],
    [p3a11_vl, p3b11d03_vl, p3b11d05_vl],
    [p3a11_va, p3b11d03_va, p3b11d05_va],
    'P3B: ResNet-11 - Baseline vs Dropout',
    labels=['RN11 Baseline', 'RN11 p=0.3', 'RN11 p=0.5']
)
plot_curves(
    [p3a18_tl, p3b18d03_tl, p3b18d05_tl],
    [p3a18_vl, p3b18d03_vl, p3b18d05_vl],
    [p3a18_va, p3b18d03_va, p3b18d05_va],
    'P3B: ResNet-18 - Baseline vs Dropout',
    labels=['RN18 Baseline', 'RN18 p=0.3', 'RN18 p=0.5']
)

# ============================================================
# FINAL GRAND COMPARISON (best variants of each architecture)
# ============================================================
best_alex  = max(p1a_test_acc, p1b03_test, p1b05_test)
best_vgg   = max(p2a_test_acc, p2b03_test, p2b05_test)
best_rn11  = max(p3a11_test, p3b11d03_test, p3b11d05_test)
best_rn18  = max(p3a18_test, p3b18d03_test, p3b18d05_test)

names  = ['ModAlexNet', 'AdapVGG-11', 'ResNet-11', 'ResNet-18']
scores = [best_alex, best_vgg, best_rn11, best_rn18]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(names, scores, color=['steelblue','orange','green','red'])
ax.set_ylim(0, 100); ax.set_ylabel('Test Accuracy (%)')
ax.set_title('Final Comparison: Best Test Accuracy Across All Architectures')
for bar, val in zip(bars, scores):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
            f'{val:.2f}%', ha='center', va='bottom', fontsize=11)
plt.tight_layout(); plt.show()

print('\n========== FINAL SUMMARY ==========')
print(f'  Best AlexNet:   {best_alex:.2f}%')
print(f'  Best VGG-11:    {best_vgg:.2f}%')
print(f'  Best ResNet-11: {best_rn11:.2f}%')
print(f'  Best ResNet-18: {best_rn18:.2f}%')
print('\nHardware:', device)
print(f'Batch size: {BATCH_SIZE}, Seed: {SEED}')